# EURUSD Data Wrangling
## Load Data - 4 Hours


Roadmap check:

- Load Data

## objectives

By the end of this notebook, We will wrangle EUR/USD data:

1. Load Data
2. plot

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [17]:

columns = ["Date","Time", "Open", "High", "Low", "Close", "Volume"]

eurusd = pd.read_csv(
    "DATA//EURUSD240.csv",
    header=None,
    names=columns
)

eurusd["DateTime"] = pd.to_datetime(
    eurusd["Date"] + " " + eurusd["Time"],
    format="%Y.%m.%d %H:%M"
)
eurusd = eurusd.set_index("DateTime")
eurusd = eurusd.sort_index()

eurusd.head()

                           Date   Time    Open    High     Low   Close  Volume
DateTime
2009-12-21 00:00:00  2009.12.21  00:00  1.4311  1.4347  1.4311  1.4342    5504
2009-12-21 04:00:00  2009.12.21  04:00  1.4342  1.4357  1.4327  1.4334    5234
2009-12-21 08:00:00  2009.12.21  08:00  1.4334  1.4342  1.4280  1.4337    8366
2009-12-21 12:00:00  2009.12.21  12:00  1.4337  1.4371  1.4330  1.4333    8456
2009-12-21 16:00:00  2009.12.21  16:00  1.4332  1.4335  1.4286  1.4294    8488

In [22]:
import pandas as pd

columns = [
    "Date",
    "Time",
    "Open",
    "High",
    "Low",
    "Close",
    "Volume"
]

eurusd = pd.read_csv(
    "DATA/EURUSD240.csv",
    header=None,
    names=columns
)

eurusd["DateTime"] = pd.to_datetime(
    eurusd["Date"] + " " + eurusd["Time"],
    format="%Y.%m.%d %H:%M"
)

eurusd = eurusd.set_index("DateTime")

eurusd = eurusd.drop(columns=["Date", "Time"])

eurusd = eurusd.sort_index()

eurusd.head()

                       Open    High     Low   Close  Volume
DateTime
2009-12-21 00:00:00  1.4311  1.4347  1.4311  1.4342    5504
2009-12-21 04:00:00  1.4342  1.4357  1.4327  1.4334    5234
2009-12-21 08:00:00  1.4334  1.4342  1.4280  1.4337    8366
2009-12-21 12:00:00  1.4337  1.4371  1.4330  1.4333    8456
2009-12-21 16:00:00  1.4332  1.4335  1.4286  1.4294    8488

In [23]:
eurusd.index.to_series().diff().value_counts().head(10)

DateTime
0 days 04:00:00    12887
2 days 04:00:00      438
1 days 08:00:00        4
3 days 08:00:00        2
0 days 16:00:00        2
0 days 08:00:00        2
1 days 16:00:00        2
3 days 12:00:00        2
3 days 04:00:00        2
1 days 12:00:00        2
Name: count, dtype: int64

In [25]:
print(pd.infer_freq(eurusd.index))

None

In [26]:
eurusd.index.to_series().diff().mode()

0   0 days 04:00:00
Name: DateTime, dtype: timedelta64[us]

In [27]:
print("First observation:", eurusd.index.min())
print("Last observation :", eurusd.index.max())
print("Number of candles:", len(eurusd))
print("Base interval:", eurusd.index.to_series().diff().mode()[0])

First observation: 2009-12-21 00:00:00
Last observation : 2026-09-01 12:00:00
Number of candles: 13351
Base interval: 0 days 04:00:00